version: '2.1'

services:
  product:
    build: microservices/product
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  recommendation:
    build: microservices/recommendation
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  review:
    build: microservices/review
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  composite-product:
    build: microservices/product-composite
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker